apiVersion: v1
kind: ConfigMap
metadata:
  name: transport-config
  namespace: transport-staging
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transport-config
  namespace: transport-prod
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  LOG_LEVEL: "INFO"
