apiVersion: v1
kind: Secret
metadata:
  name: transport-secrets
  namespace: transport-staging
stringData:
  JWT_SECRET: "change-me-staging"
  DB_URL: "jdbc:postgresql://postgres:5432/transport"
  DB_USER: "user"
  DB_PASS: "pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: transport-secrets
  namespace: transport-prod
stringData:
  JWT_SECRET: "change-me-prod"
  DB_URL: "jdbc:postgresql://postgres:5432/transport"
  DB_USER: "user"
  DB_PASS: "pass"
